name: Reusable Deploy Migrations Workflow

on:
  workflow_call:
    inputs:
      DOCKER_IMAGE_TAG:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      K8s_SERVICE:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ACCESS_KEY_ID:
        required: true
      AWS_ACCOUNT_SECRET_ACCESS_KEY:
        required: true
      PAT:
        required: true

env:
  GITHUB_SHA: ${{ github.sha }}

jobs:
  deploy_migrations:
    name: "${{ inputs.ENVIRONMENT }} Migrations Deploy"
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS credentials for Migrations Deploy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCOUNT_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCOUNT_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Checkout repo wheel-deploys
        uses: actions/checkout@v2
        with:
          repository: enzyme-health/wheel-deploys
          token: ${{ secrets.PAT }}
          path: wheel-deploys

      - name: Pin terraform version
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          terraform_wrapper: false

      - uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.23.6'
        id: install

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "4.5.7"

      - name: Kustomize update the Image tag for Environment
        run: |
          kustomize version --short
          pushd wheel-deploys/k8s/${K8S_SERVICE}/overlays/${ENVIRONMENT}
          kustomize edit set image 021057518589.dkr.ecr.us-west-2.amazonaws.com/${K8S_SERVICE}-migrations:{GITHUB_SHA}
        env:
          ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
          K8S_SERVICE: ${{ env.K8S_SERVICE }}

      - name: Commit files
        run: |
          git commit -am "Bump docker tag"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup AWS EKS Credentials
        run: |
          aws --version
          aws eks --region us-west-2 update-kubeconfig --name opta-${ENVIRONMENT}2
        env:
          ENVIRONMENT: ${{ inputs.ENVIRONMENT }}

      - name: Update deployment via Opta
        run: |
          kubectl version --client --short
          kubectl apply -k  overlays/${ENVIRONMENT}/kustomize.yaml
        env:
          ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
