name: Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      DOCKER_IMAGE_TAG:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      OPTA_FILE:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ACCESS_KEY_ID:
        required: true
      AWS_ACCOUNT_SECRET_ACCESS_KEY:
        required: true
      PAT:
        required: true

concurrency:
  group: "${{ inputs.ENVIRONMENT }}-${{ inputs.OPTA_FILE }}-deploy"
  cancel-in-progress: true

env:
  GITHUB_SHA: ${{ github.sha }}

jobs:
  opta-deploy:
    name: "Opta ${{ inputs.ENVIRONMENT }} Deploy"
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS credentials for Opta Deploy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCOUNT_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCOUNT_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Checkout repo wheel-deploys
        uses: actions/checkout@v2
        with:
          repository: enzyme-health/wheel-deploys
          token: ${{ secrets.PAT }}
          path: wheel-deploys

      - name: Pin terraform version
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          terraform_wrapper: false

      - name: Install Opta tools
        run: |
          VERSION=0.40.0 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/enzyme-health/opta/refs/tags/v0.40.0/install.sh)"
      - name: Set Opta Configuration File Path
        run: |
          echo "OPTA_CONFIG_FILE=wheel-deploys/opta/$ENVIRONMENT/$OPTA_FILE" >> $GITHUB_ENV
        env:
          ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
          OPTA_FILE: ${{ inputs.OPTA_FILE }}

      - uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.25.16'
        id: install

      - name: Update deployment via Opta
        id: opta-deploy
        run: |
          kubectl version --client --short
          aws --version
          opta apply -c $OPTA_CONFIG_FILE --var image-tag=$DOCKER_IMAGE_TAG --image-tag $DOCKER_IMAGE_TAG --auto-approve
          echo "Deployed $DOCKER_IMAGE_TAG to $ENVIRONMENT"
        env:
          OPTA_HOTFIX_EXEC_CREDENTIAL_VERSION: client.authentication.k8s.io/v1beta1
          OPTA_CONFIG_FILE: ${{ env.OPTA_CONFIG_FILE }}
          DOCKER_IMAGE_TAG: ${{ inputs.DOCKER_IMAGE_TAG }}
          ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
